"use client";

import { useState, useEffect, useRef } from "react";
import sdk from "@stackblitz/sdk";
import JSZip from "jszip";
import FeatureLayout from "../components/FeatureLayout";
import { api } from "@/lib/api";

type FileEntry = { path: string; content: string };

const FRAMEWORKS = [
  { id: "react", label: "React", desc: "SPA with Vite/CRA" },
  { id: "next", label: "Next.js", desc: "React full-stack" },
  { id: "streamlit", label: "Streamlit", desc: "Python data apps" },
  { id: "node", label: "Node / Express", desc: "Backend or SSR" },
  { id: "python", label: "Python / FastAPI", desc: "API or script" },
  { id: "vue", label: "Vue", desc: "Vue 3" },
  { id: "svelte", label: "Svelte", desc: "SvelteKit" },
];

const WEB_FRAMEWORKS = ["react", "next", "vue", "svelte"];

function buildStackBlitzFiles(files: FileEntry[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const f of files) {
    out[f.path] = f.content;
  }
  const pkg = files.find((x) => x.path === "package.json");
  if (pkg) {
    try {
      const parsed = JSON.parse(pkg.content);
      const scripts = parsed.scripts || {};
      const startCmd =
        scripts.dev || scripts.start || (scripts.build ? "npm run build && npm start" : "npm start");
      parsed.stackblitz = {
        installDependencies: true,
        startCommand: startCmd,
      };
      out["package.json"] = JSON.stringify(parsed, null, 2);
    } catch {
      // keep original
    }
  }
  return out;
}


export default function CodeGenPage() {
  const [prompt, setPrompt] = useState("");
  const [framework, setFramework] = useState("react");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<{ files: FileEntry[]; instructions: string } | null>(null);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [embedReady, setEmbedReady] = useState(false);
  const embedRef = useRef<HTMLDivElement>(null);

  const canEmbed = result && WEB_FRAMEWORKS.includes(framework) && result.files.some((f) => f.path === "package.json");

  useEffect(() => {
    if (!canEmbed || !result || !embedRef.current) return;
    setEmbedReady(false);
    embedRef.current.innerHTML = "";
    const files = buildStackBlitzFiles(result.files);
    sdk
      .embedProject(
        embedRef.current,
        {
          title: "Generated by Code Gen",
          description: prompt.slice(0, 100),
          template: "node",
          files,
        },
        {
          view: "preview",
          hideExplorer: true,
          hideDevTools: true,
          terminalHeight: 0,
        }
      )
      .then(() => setEmbedReady(true))
      .catch(() => setEmbedReady(false));
  }, [result, framework, prompt, canEmbed]);

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!prompt.trim() || loading) return;
    setLoading(true);
    setError(null);
    setResult(null);
    setSelectedFile(null);
    try {
      const res = await fetch(api("/api/codegen/generate"), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim(), framework }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail ?? `HTTP ${res.status}`);
      setResult(data);
      if (data.files?.length) setSelectedFile(data.files[0].path);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Generation failed");
    } finally {
      setLoading(false);
    }
  }

  const currentContent = result?.files?.find((f) => f.path === selectedFile)?.content ?? "";

  return (
    <FeatureLayout
      title="Code Gen"
      description="Generate full websites or apps with Streamlit, React, Node, Python, or any supported framework. Uses Context7 for live docs; run your project in Vercel Sandbox."
      icon="⚡"
      endpoints={[{ method: "POST", path: "/api/codegen/generate" }]}
    >
      <div className="codegenHero">
        <h1 className="codegenHeroTitle">Build apps in seconds</h1>
        <p className="codegenHeroSubtitle">
          Describe what you want — get runnable code. Context7 docs built-in; run in Vercel Sandbox or copy files.
        </p>
      </div>

      <div className="codegenHowItWorks">
        <span className="codegenHowStep"><strong>1</strong> Describe + framework</span>
        <span className="codegenHowArrow">→</span>
        <span className="codegenHowStep"><strong>2</strong> Generate</span>
        <span className="codegenHowArrow">→</span>
        <span className="codegenHowStep"><strong>3</strong> Run in Sandbox or copy</span>
      </div>

      <div className="featureCard">
        <div className="cardHeader">
          <h2>
            <span className="cardIcon">⚡</span>
            Generate a project
          </h2>
        </div>
        <p className="featureCardSubtitle">
          Describe what you want to build and pick a framework. Code is generated with Context7 docs and ready for Vercel Sandbox.
        </p>

        <form className="featureForm" onSubmit={handleGenerate}>
          <div>
            <label htmlFor="codegen-prompt">What do you want to build?</label>
            <textarea
              id="codegen-prompt"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. A todo app with dark mode and local storage — or describe any app idea"
              rows={3}
            />
          </div>
          <div>
            <label>Framework</label>
            <div className="codegenFrameworkGrid">
              {FRAMEWORKS.map((fw) => (
                <button
                  key={fw.id}
                  type="button"
                  className={`modePill ${framework === fw.id ? "active" : ""}`}
                  onClick={() => setFramework(fw.id)}
                >
                  {fw.label}
                </button>
              ))}
            </div>
          </div>
          <button type="submit" className="featureBtn featureBtnPrimary" disabled={loading || !prompt.trim()}>
            {loading ? <span className="loadingDot">Generating</span> : "Generate project"}
          </button>
        </form>

        {error && (
          <div className="featureResult featureError" style={{ marginTop: 16 }}>
            {error}
          </div>
        )}

        {result && (
          <div className="codegenResult">
            {/* Live preview showcase */}
            {canEmbed ? (
              <div className="codegenShowcase">
                <div className="codegenShowcaseHeader">
                  <h3>Live preview</h3>
                  <span className="codegenShowcaseBadge">Your generated site</span>
                </div>
                <div
                  ref={embedRef}
                  className={`codegenShowcaseEmbed ${embedReady ? "loaded" : ""}`}
                  style={{ minHeight: 480 }}
                />
                {!embedReady && (
                  <div className="codegenShowcaseLoading">Loading preview…</div>
                )}
              </div>
            ) : (
              <div className="codegenShowcase codegenShowcaseFallback">
                <div className="codegenShowcaseHeader">
                  <h3>Generated project</h3>
                  <p className="featureCardSubtitle" style={{ margin: 0 }}>
                    Run locally: {result.instructions?.split(".")[0] || "See instructions below."}
                  </p>
                </div>
              </div>
            )}

            {result.instructions && (
              <div className="codegenInstructions">
                <strong>How to run</strong>
                <p>{result.instructions}</p>
              </div>
            )}

            <div className="codegenActions">
              <button
                type="button"
                className="featureBtn featureBtnSecondary"
                onClick={() => {
                  const zip = new JSZip();
                  for (const f of result.files) {
                    zip.file(f.path, f.content);
                  }
                  zip.generateAsync({ type: "blob" }).then((blob: Blob) => {
                    const a = document.createElement("a");
                    a.href = URL.createObjectURL(blob);
                    a.download = "generated-project.zip";
                    a.click();
                    URL.revokeObjectURL(a.href);
                  });
                }}
              >
                📦 Download project
              </button>
              <button
                type="button"
                className="featureBtn featureBtnSecondary"
                onClick={() => {
                  if (!result || !canEmbed) return;
                  const files = buildStackBlitzFiles(result.files);
                  sdk.openProject(
                    {
                      title: "Generated by Code Gen",
                      description: prompt.slice(0, 100),
                      template: "node",
                      files,
                    },
                    { newWindow: true }
                  );
                }}
                disabled={!canEmbed}
              >
                Open in StackBlitz →
              </button>
            </div>

            <div className="codegenGitHubSection">
              <h4>Add to GitHub</h4>
              <ol className="codegenGitHubSteps">
                <li>Download the project above and unzip it</li>
                <li>Create a new repo on <a href="https://github.com/new" target="_blank" rel="noopener noreferrer">GitHub</a></li>
                <li>Run in terminal:
                  <pre className="codegenGitHubCmd">
{`cd generated-project
git init
git add .
git commit -m "Initial commit"
git branch -M main
git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
git push -u origin main`}
                  </pre>
                </li>
              </ol>
            </div>

            <div className="splitPanel" style={{ marginTop: 16 }}>
              <div className="codegenFileList">
                <div className="codegenFileListTitle">Files</div>
                {result.files.map((f) => (
                  <button
                    key={f.path}
                    type="button"
                    className={`codegenFileItem ${selectedFile === f.path ? "active" : ""}`}
                    onClick={() => setSelectedFile(f.path)}
                  >
                    {f.path}
                  </button>
                ))}
              </div>
              <div className="codegenEditor">
                <pre className="codegenPre">
                  <code>{currentContent}</code>
                </pre>
                <button
                  type="button"
                  className="featureBtn featureBtnSecondary"
                  style={{ marginTop: 8 }}
                  onClick={() => {
                    navigator.clipboard.writeText(currentContent);
                  }}
                >
                  Copy file
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </FeatureLayout>
  );
}
