import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const html = await readFile(resolve(root, "site/index.html"), "utf8");
const adapter = await readFile(resolve(root, "site/graft-adapter.js"), "utf8");
const bootstrap = await readFile(resolve(root, "site/omnidev-webmcp.js"), "utf8");
const sha256 = (value) => createHash("sha256").update(value).digest("hex");
const assert = (condition, message) => {
  if (!condition) throw new Error(message);
};
const expectedGraftRevision = "db4133b";
const runtimePrefix =
  "/* ---- Graft runtime, inlined. No network calls, no dependency on Graft. ---- */\n";
const runtimeSuffix = "\n/* ---- end runtime ---- */";
const runtimeStart = adapter.indexOf(runtimePrefix);
const runtimeEnd = adapter.indexOf(runtimeSuffix, runtimeStart + runtimePrefix.length);
assert(runtimeStart >= 0 && runtimeEnd > runtimeStart, "Could not delimit the inlined Graft runtime.");
const inlinedRuntime = adapter.slice(runtimeStart + runtimePrefix.length, runtimeEnd);

const exportedJson = (name, nextDeclaration) => {
  const prefix = `export const ${name} = `;
  const start = adapter.indexOf(prefix);
  assert(start >= 0, `Missing ${name} export.`);
  const valueStart = start + prefix.length;
  const suffix = `;\n\n${nextDeclaration}`;
  const end = adapter.indexOf(suffix, valueStart);
  assert(end >= 0, `Could not delimit ${name}.`);
  return JSON.parse(adapter.slice(valueStart, end));
};

const manifest = exportedJson("graftManifest", "export const graftTools");
const tools = exportedJson("graftTools", "export async function registerGraftTools");
const expectedNames = [
  "get_page_summary",
  "get_page_outline",
  "list_capabilities",
  "show_capability",
];
const expectedSectionIds = [
  "file-search",
  "local-mcp",
  "agent-mode",
  "destructive-guards",
  "secret-guards",
  "specification",
];

assert(manifest.product === "Graft", "Adapter manifest is not a Graft export.");
assert(manifest.source?.url === "https://omnidev-flame.vercel.app/", "Owner URL drifted.");
assert(
  manifest.provenance?.sourceHtmlSha256 === sha256(html),
  "site/index.html changed without regenerating site/graft-adapter.js.",
);
assert(
  manifest.provenance?.graftRevision === expectedGraftRevision,
  `Adapter was not generated by reviewed Graft revision ${expectedGraftRevision}.`,
);
assert(
  manifest.provenance?.runtimeSha256 === sha256(inlinedRuntime),
  "Inlined runtime bytes do not match their Graft provenance hash.",
);
assert(
  manifest.provenance?.exportedToolsSha256 === sha256(JSON.stringify(tools)),
  "Exported tool payload does not match its provenance hash.",
);
assert(
  JSON.stringify(tools.map((tool) => tool.name)) === JSON.stringify(expectedNames),
  "The live tool set is not the reviewed four-tool surface.",
);
assert(
  JSON.stringify(manifest.tools.map((tool) => tool.name)) === JSON.stringify(expectedNames),
  "The manifest contains unexpected held or rejected compiler noise.",
);
assert(manifest.tools.every((tool) => tool.status === "auto"), "Every candidate must be auto.");
assert(
  tools.every(
    (tool) =>
      /^[a-z][a-z0-9_]{0,29}$/.test(tool.name) &&
      tool.inputSchema?.additionalProperties === false &&
      tool.annotations?.untrustedContentHint === true,
  ),
  "A generated descriptor is malformed or missing its untrusted-content annotation.",
);

const list = tools.find((tool) => tool.name === "list_capabilities");
const show = tools.find((tool) => tool.name === "show_capability");
assert(list?.binding?.kind === "section_group", "list_capabilities lost its R8 binding.");
assert(show?.binding?.kind === "show_section", "show_capability lost its R8 binding.");
assert(list.annotations?.readOnlyHint === true, "list_capabilities must be read-only.");
assert(show.annotations?.readOnlyHint === false, "show_capability must declare its viewport effect.");
assert(show.destructive === false, "show_capability must remain non-destructive.");
assert(show.action === "local_navigation", "show_capability must remain a local navigation action.");
assert(
  JSON.stringify(list.binding.sectionIds) === JSON.stringify(expectedSectionIds),
  "list_capabilities allowlist drifted.",
);
assert(
  JSON.stringify(show.inputSchema.properties.id.enum) === JSON.stringify(expectedSectionIds),
  "show_capability enum drifted.",
);
assert(
  JSON.stringify(show.binding.sectionIds) === JSON.stringify(expectedSectionIds),
  "show_capability runtime allowlist drifted.",
);

const sectionTags = [...html.matchAll(/<section\b[^>]*>/g)].map((match) => match[0]);
for (const id of expectedSectionIds) {
  const tag = sectionTags.find((candidate) => candidate.includes(`id="${id}"`));
  assert(tag?.includes('data-graft-section="capability"'), `Missing semantic marker for ${id}.`);
}
assert(html.includes('src="omnidev-webmcp.js"'), "The owner bootstrap is not loaded.");
assert(!html.includes("owner-bound action"), "Stale owner-authored action copy remains.");
assert(!/\.registerTool\s*\(/.test(bootstrap), "The owner bootstrap declares a tool directly.");
assert(!/\bexecute\s*:/.test(bootstrap), "The owner bootstrap contains a custom tool handler.");
assert(
  bootstrap.includes("await registerGraftTools()"),
  "The owner bootstrap does not register the generated adapter.",
);

const registered = [];
const unregistered = [];
globalThis.document = {
  modelContext: {
    registerTool: async (descriptor) => registered.push(descriptor),
    unregisterTool: async (name) => unregistered.push(name),
  },
};
const adapterModule = await import(
  `data:text/javascript;base64,${Buffer.from(adapter).toString("base64")}`
);
const report = await adapterModule.registerGraftTools();
assert(report.failures.length === 0, "Generated adapter registration reported a failure.");
assert(report.missingHandlers.length === 0, "Generated adapter is missing a runtime handler.");
assert(
  JSON.stringify(report.registered) === JSON.stringify(expectedNames),
  "Generated adapter did not register the reviewed tool set.",
);
assert(
  JSON.stringify(registered.map((tool) => tool.name)) === JSON.stringify(expectedNames),
  "Native descriptors do not match graftTools.",
);
await report.cleanup();
assert(unregistered.length === expectedNames.length, "Generated adapter cleanup is incomplete.");

console.log("WebMCP adapter provenance, contract and registration checks passed.");
