import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const html = await readFile(resolve(root, "site/index.html"), "utf8");
const adapter = await readFile(resolve(root, "site/graft-adapter.js"), "utf8");
const adapterDigest = await readFile(resolve(root, "site/graft-adapter.js.sha256"), "utf8");
const bootstrap = await readFile(resolve(root, "site/omnidev-webmcp.js"), "utf8");
const sha256 = (value) => createHash("sha256").update(value).digest("hex");
const EXPECTED_GRAFT_REVISION = "4c5b77c5386a020c40d248db948db562d4d7ebcf";
const EXPECTED_GENERATOR_SOURCES_SHA256 =
  "254102341e0b0d0568c26a167158a80cf88ea6c436a115f905d7fa4ad97a881a";
const assert = (condition, message) => {
  if (!condition) throw new Error(message);
};
const runtimePrefix =
  "/* ---- Graft runtime, inlined. No network calls, no dependency on Graft. ---- */\n";
const runtimeSuffix = "\n/* ---- end runtime ---- */";
const runtimeStart = adapter.indexOf(runtimePrefix);
const runtimeEnd = adapter.indexOf(runtimeSuffix, runtimeStart + runtimePrefix.length);
assert(runtimeStart >= 0 && runtimeEnd > runtimeStart, "Could not delimit the inlined Graft runtime.");
const inlinedRuntime = adapter.slice(runtimeStart + runtimePrefix.length, runtimeEnd);

const exportedJson = (name) => {
  const prefix = `export const ${name} = `;
  const start = adapter.indexOf(prefix);
  assert(start >= 0, `Missing ${name} export.`);
  let valueStart = start + prefix.length;
  while (/\s/.test(adapter[valueStart])) valueStart += 1;
  assert(
    adapter[valueStart] === "{" || adapter[valueStart] === "[",
    `${name} is not a JSON object or array.`,
  );

  const stack = [];
  let inString = false;
  let escaped = false;
  for (let index = valueStart; index < adapter.length; index += 1) {
    const character = adapter[index];
    if (inString) {
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === '"') inString = false;
      continue;
    }
    if (character === '"') {
      inString = true;
      continue;
    }
    if (character === "{") stack.push("}");
    else if (character === "[") stack.push("]");
    else if (character === "}" || character === "]") {
      assert(character === stack.pop(), `Unbalanced JSON while reading ${name}.`);
      if (stack.length === 0) return JSON.parse(adapter.slice(valueStart, index + 1));
    }
  }
  throw new Error(`Could not delimit ${name}.`);
};

const manifest = exportedJson("graftManifest");
const tools = exportedJson("graftTools");
const expectedNames = [
  "get_page_summary",
  "get_page_outline",
  "list_capabilities",
  "show_capability",
];
const expectedSectionIds = [
  "file-search",
  "local-mcp",
  "agent-mode",
  "destructive-guards",
  "secret-guards",
  "specification",
];

assert(manifest.product === "Graft", "Adapter manifest is not a Graft export.");
assert(manifest.source?.url === "https://omnidev-flame.vercel.app/", "Owner URL drifted.");
assert(
  manifest.provenance?.sourceHtmlSha256 === sha256(html),
  "site/index.html changed without regenerating site/graft-adapter.js.",
);
assert(
  manifest.provenance?.graftRevision === EXPECTED_GRAFT_REVISION,
  "Adapter was not generated by the pinned reviewed Graft commit.",
);
assert(
  manifest.provenance?.graftSourceState === "clean",
  "Adapter was generated from a dirty Graft working tree.",
);
assert(
  manifest.provenance?.generatorSourcesSha256 === EXPECTED_GENERATOR_SOURCES_SHA256,
  "Adapter generator source hash does not match the pinned reviewed Graft source.",
);
assert(
  manifest.provenance?.runtimeSha256 === sha256(inlinedRuntime),
  "Inlined runtime bytes do not match their Graft provenance hash.",
);
assert(
  manifest.provenance?.exportedToolsSha256 === sha256(JSON.stringify(tools)),
  "Exported tool payload does not match its provenance hash.",
);
assert(
  adapterDigest === `${sha256(adapter)}  graft-adapter.js\n`,
  "Adapter bytes do not match their detached SHA-256 digest.",
);
assert(
  !/\b(?:fetch|eval)\s*\(|\b(?:XMLHttpRequest|WebSocket|EventSource|indexedDB|localStorage|sessionStorage)\b|new\s+Function\b|document\.cookie/.test(
    adapter,
  ),
  "Generated adapter introduced network, dynamic-code, storage or cookie access.",
);
assert(
  JSON.stringify(tools.map((tool) => tool.name)) === JSON.stringify(expectedNames),
  "The live tool set is not the reviewed four-tool surface.",
);
assert(
  JSON.stringify(manifest.tools.map((tool) => tool.name)) === JSON.stringify(expectedNames),
  "The manifest contains unexpected held or rejected compiler noise.",
);
assert(manifest.tools.every((tool) => tool.status === "auto"), "Every candidate must be auto.");
assert(
  tools.every(
    (tool) =>
      /^[a-z][a-z0-9_]{0,29}$/.test(tool.name) &&
      tool.inputSchema?.additionalProperties === false &&
      tool.annotations?.untrustedContentHint === true,
  ),
  "A generated descriptor is malformed or missing its untrusted-content annotation.",
);

const list = tools.find((tool) => tool.name === "list_capabilities");
const show = tools.find((tool) => tool.name === "show_capability");
assert(list?.binding?.kind === "section_group", "list_capabilities lost its R8 binding.");
assert(show?.binding?.kind === "show_section", "show_capability lost its R8 binding.");
assert(list.annotations?.readOnlyHint === true, "list_capabilities must be read-only.");
assert(show.annotations?.readOnlyHint === false, "show_capability must declare its viewport effect.");
assert(show.destructive === false, "show_capability must remain non-destructive.");
assert(show.action === "local_navigation", "show_capability must remain a local navigation action.");
assert(
  JSON.stringify(list.binding.sectionIds) === JSON.stringify(expectedSectionIds),
  "list_capabilities allowlist drifted.",
);
assert(
  JSON.stringify(show.inputSchema.properties.id.enum) === JSON.stringify(expectedSectionIds),
  "show_capability enum drifted.",
);
assert(
  JSON.stringify(show.binding.sectionIds) === JSON.stringify(expectedSectionIds),
  "show_capability runtime allowlist drifted.",
);

const sectionTags = [...html.matchAll(/<section\b[^>]*>/g)].map((match) => match[0]);
for (const id of expectedSectionIds) {
  const tag = sectionTags.find((candidate) => candidate.includes(`id="${id}"`));
  assert(tag?.includes('data-graft-section="capability"'), `Missing semantic marker for ${id}.`);
}
assert(html.includes('src="omnidev-webmcp.js"'), "The owner bootstrap is not loaded.");
assert(html.includes('id="webmcp-status"'), "The quiet WebMCP trust marker is missing.");
assert(html.includes("WebMCP via Graft"), "The public Graft provenance marker is missing.");
assert(!html.includes('class="agent-surface"'), "The verbose public agent surface returned.");
assert(!html.includes('id="webmcp-receipt"'), "The public tool receipt returned.");
assert(!html.includes('id="webmcp-registry-status"'), "The duplicate registry status returned.");
assert(!html.includes("owner-bound action"), "Stale owner-authored action copy remains.");
assert(!/\.registerTool\s*\(/.test(bootstrap), "The owner bootstrap declares a tool directly.");
assert(!/\bexecute\s*:/.test(bootstrap), "The owner bootstrap contains a custom tool handler.");
assert(
  bootstrap.includes("await registerGraftTools()"),
  "The owner bootstrap does not register the generated adapter.",
);

const registered = [];
const unregistered = [];
globalThis.document = {
  modelContext: {
    registerTool: async (descriptor) => registered.push(descriptor),
    unregisterTool: async (name) => unregistered.push(name),
  },
};
const adapterModule = await import(
  `data:text/javascript;base64,${Buffer.from(adapter).toString("base64")}`
);
const report = await adapterModule.registerGraftTools();
assert(report.failures.length === 0, "Generated adapter registration reported a failure.");
assert(report.missingHandlers.length === 0, "Generated adapter is missing a runtime handler.");
assert(
  JSON.stringify(report.registered) === JSON.stringify(expectedNames),
  "Generated adapter did not register the reviewed tool set.",
);
assert(
  JSON.stringify(registered.map((tool) => tool.name)) === JSON.stringify(expectedNames),
  "Native descriptors do not match graftTools.",
);
await report.cleanup();
assert(unregistered.length === expectedNames.length, "Generated adapter cleanup is incomplete.");

console.log("WebMCP adapter provenance, contract and registration checks passed.");
